apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test02-appplication-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/chiune/test-argocd-02.git
    targetRevision: HEAD
    path: environments/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: test02-app-dev
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true