apiVersion: apps/v1
kind: Deployment
metadata:
  name: all-resources
spec:
  template:
    spec:
      containers:
        - name: postgres
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
