apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  template:
    spec:
      containers:
        - resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
