apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#namePrefix: dev-

bases:
  - ../../application

patches:
  - db-resources.yaml

configMapGenerator:
  - name: config
    literals:
      - env=dev
  - name: db-config
    files: 
      - configs/db-config.json